In [2]:
import numpy as np

x = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x.reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
x = np.array([],dtype='i')
for i in range(16):
    x = np.append(x,[1],axis=0)
x = x.reshape(4,4)

for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if (i>0 and i<x.shape[0]-1) and (j>0 and j<x.shape[1]-1):
            x[i][j] = 0

print(x)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [46]:
st = np.array([('Adi', 5, 48.5 ), ('Budi', 6, 52.5 ), ('Heni', 5, 42.1 )],
                dtype=[('nama','U10'),('kelas','i'),('tinggi','f')])
st.sort(order='tinggi')
print(st)

[('Heni', 5, 42.1) ('Adi', 5, 48.5) ('Budi', 6, 52.5)]


In [51]:
monyet = np.dtype([('nama','U10'),('kelas','i'),('tinggi','f'),('nilai','i')])
nilai = np.array([70.6,60.1,40.3])
for i in st:
    monyet['nama'] = st['nama']
    monyet['kelas'] = st['kelas']
    monyet['tinggi'] = st['tinggi']
monyet.nilai = nilai
print(monyet)

TypeError: 'numpy.dtype' object does not support item assignment

In [15]:
from numpy import random

arr = np.array([],dtype='i')
while arr.size<10:
  x = random.randint(10)
  y = np.where(arr==x)
  if y[0].size==0:
    arr = np.append(arr,x)
print(arr)

[1 0 8 2 4 7 9 5 6 3]
