In [2]:
import numpy as np

x = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x.reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
x = np.array([],dtype='i')
for i in range(16):
    x = np.append(x,[1],axis=0)
x = x.reshape(4,4)

for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        if (i>0 and i<x.shape[0]-1) and (j>0 and j<x.shape[1]-1):
            x[i][j] = 0

print(x)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [4]:
st = np.array([('Adi', 5, 48.5 ), ('Budi', 6, 52.5 ), ('Heni', 5, 42.1 )],
                dtype=[('nama','U10'),('kelas','i'),('tinggi','f')])
st.sort(order='tinggi')
print(st)

[('Heni', 5, 42.1) ('Adi', 5, 48.5) ('Budi', 6, 52.5)]


In [5]:
nilai = np.array([70.6,60.1,40.3],dtype='f')
newSt = np.array([(st[0]['nama'],st[0]['kelas'],st[0]['tinggi'],nilai[0])],dtype=[('nama','U10'),('kelas','i'),('tinggi','f'),('nilai','f')])
for i in range(st.size):
    tambah = np.array([(st[i]['nama'],st[i]['kelas'],st[i]['tinggi'],nilai[i])],
    dtype=[('nama','U10'),('kelas','i'),('tinggi','f'),('nilai','f')])
    newSt = np.append(newSt,tambah)
newSt = np.array(newSt[1:])
print(newSt)

[('Heni', 5, 42.1, 70.6) ('Adi', 5, 48.5, 60.1) ('Budi', 6, 52.5, 40.3)]


In [6]:
rataan = np.average(newSt[:]['nilai'])
index = np.where(newSt[:]['nilai']>rataan)
newSt = newSt[index[0][0]:index[0][1]+1]
print(newSt)

[('Heni', 5, 42.1, 70.6) ('Adi', 5, 48.5, 60.1)]


In [7]:
from numpy import random

arr = np.array([],dtype='i')
while arr.size<10:
  x = random.randint(10)
  y = np.where(arr==x)
  if y[0].size==0:
    arr = np.append(arr,x)
print(arr)

[8 9 6 4 0 7 3 1 5 2]


In [8]:
result = np.where(arr==5)
print(result[0])

[8]


In [9]:
arr = arr.reshape(2,5)
print(arr)

[[8 9 6 4 0]
 [7 3 1 5 2]]


In [26]:
print(arr[:,2:5])

[[6 4 0]
 [1 5 2]]


In [28]:
x = np.sum(arr[0])
y = np.sum(arr[1])
if x>y:
    print("Baris ke-1 lebih besar")
elif x<y:
    print("Baris ke-1 lebih kecil")
else:
    print("Jumlah sama")

Baris ke-1 lebih besar


In [33]:
arr = arr.astype("f")
print(arr)
print(arr.dtype)

[[8. 9. 6. 4. 0.]
 [7. 3. 1. 5. 2.]]
float32
